### ISSUE TITLE
Can you deploy a 0.4 stable into some maven repository

### ISSUE THREAD

**Issue by ouaibsky** [bmoussaud/placeholders-mustachifier-maven-plugin#3]
Hi

Can you deploy a 0.4 inside an "official" repository like oss sonatype please ?
Thx
Christophe Lallement

**Comment by bmoussaud** [comment]
I've started the process to publish it ....

**Comment by bmoussaud** [comment]
Released 0.4 is now deployed on maven central site
@ouaibsky can you test ?

**Comment by ouaibsky** [comment]
Hey

Looks like it works, Thx
Christophe

**Comment by bmoussaud** [comment]
thank you
